#!/usr/bin/env python3
"""Concatenate content/ + lab READMEs into per-phase NotebookLM packs.

Direction is one-way: repo → build/. Nothing writes back into content/.

    python tools/studypack.py
    python tools/studypack.py --phase 3
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content"
LABS = ROOT / "labs"
BUILD = ROOT / "build"

# One pack per PLAN phase. Phase 1 includes Lab 00 (the Phase 0 exemplar).
PHASES: dict[int, dict] = {
    1: {
        "title": "Control",
        "lectures": ["L01", "L02", "L03", "L04", "L05"],
        "labs": [
            "lab00_hello_state",
            "lab01_planar_dynamics",
            "lab02_into_3d",
            "lab03_cascade_pd",
            "lab04_lqr",
        ],
    },
    2: {
        "title": "Planning",
        "lectures": ["L06", "L07", "L08", "L09", "L10"],
        "labs": [
            "lab05_search_visualized",
            "lab06_heuristics",
            "lab07_rrt",
            "lab08_flatness",
            "lab09_time_scaling",
        ],
    },
    3: {
        "title": "Estimation",
        "lectures": ["L11", "L12", "L13", "L14", "L15", "L16"],
        "labs": [
            "lab10_set_belief",
            "lab11_bayes",
            "lab12_kf_pf",
            "lab13_mcl",
            "lab14_mapping",
            "lab15_slam",
        ],
    },
    4: {
        "title": "Vision, Learning, RL",
        "lectures": ["L17", "L18", "L19", "L20", "L21", "L22", "L23"],
        "labs": [
            "lab16_camera",
            "lab17_optical_flow",
            "lab18_mlp",
            "lab19_sgd",
            "lab20_overfit",
            "lab21_cnn",
            "lab22_rl",
        ],
    },
    5: {
        "title": "Reflection",
        "lectures": ["L24"],
        "labs": ["lab23_red_team"],
    },
}

FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)
NOTEBOOKLM_SOFT_LIMIT = 400_000  # chars; warn, do not truncate


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Dumb frontmatter: `key: value` lines. Lists stay as the raw string."""
    m = FRONTMATTER.match(text)
    if not m:
        return {}, text
    meta: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        meta[k.strip()] = v.strip()
    return meta, text[m.end() :]


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def pack_phase(n: int) -> Path:
    if n not in PHASES:
        raise KeyError(f"unknown phase {n}; known {sorted(PHASES)}")
    spec = PHASES[n]
    chunks = [
        f"# Study pack — Phase {n}: {spec['title']}\n",
        "Generated by `tools/studypack.py`. Source of truth is `content/` and\n"
        "`labs/*/README.md`. Do not edit this file.\n",
    ]
    for lid in spec["lectures"]:
        src = CONTENT / f"{lid}.md"
        if not src.is_file():
            chunks.append(f"\n## {lid} *(missing {src.relative_to(ROOT)})*\n")
            continue
        meta, body = split_frontmatter(_read(src))
        title = meta.get("id", lid)
        chunks.append(f"\n## Lecture {title}\n")
        if meta:
            chunks.append(
                f"*concepts:* {meta.get('concepts', '—')} · "
                f"*prereqs:* {meta.get('prereqs', '—')} · "
                f"*lab:* {meta.get('lab_id', '—')}\n"
            )
        chunks.append(body.strip() + "\n")
    for folder in spec["labs"]:
        src = LABS / folder / "README.md"
        if not src.is_file():
            chunks.append(f"\n## Lab README missing: `{folder}`\n")
            continue
        chunks.append(f"\n## Lab README — `{folder}`\n")
        chunks.append(_read(src).strip() + "\n")
    text = "\n".join(chunks)
    if len(text) > NOTEBOOKLM_SOFT_LIMIT:
        print(f"warning: phase {n} pack is {len(text)} chars (soft limit {NOTEBOOKLM_SOFT_LIMIT})", file=sys.stderr)
    BUILD.mkdir(parents=True, exist_ok=True)
    dest = BUILD / f"studypack_phase{n}.md"
    dest.write_text(text, encoding="utf-8")
    return dest


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Build per-phase NotebookLM markdown packs.")
    p.add_argument("--phase", type=int, default=0, help="single phase 1–5 (default: all)")
    args = p.parse_args(argv)
    phases = [args.phase] if args.phase else sorted(PHASES)
    for n in phases:
        dest = pack_phase(n)
        print(f"wrote {dest.relative_to(ROOT)}  ({dest.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
